name: ci
on:
  push:
    branches:
      - master
strategy:
  matrix:
    node-version: [16]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: action/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Project
        run:  npm install
      - name: Build
        run: npm run build